services:
  frontend:
    build: ./TTT-Web-Front/
    ports:
      - "11451:80"
  backend:
    depends_on:
      - redis
    build: ./TTT-Web-Back/
    deploy:
      replicas: 3
  redis:
    image: redis:alpine
