services:
  frontend:
    build: ./TTT-Web-Front/
    depends_on:
      - backend
    ports:
      - "11451:80"
  backend:
    depends_on:
      - redis
    build: ./TTT-Web-Back/
  redis:
    image: redis:alpine